---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(summarytools)
library(caret)
library("ggpubr")
```

## Load data

```{r}
languages <- c("Arabic", "Basque", "Catalan", "Chinese", "Czech", "English", "Greek", "Hungarian", "Italian", "Turkish")

table_1 <- data.frame(language=languages,
                     N = numeric(length(languages)),
                     mu_n = numeric(length(languages)),
                     sd_n = numeric(length(languages)),
                     mu_k = numeric(length(languages)),
                     sd_k = numeric(length(languages)))

for (l in 1:length(languages)) {
  lang <- languages[l]
  path <- paste("./data/",paste(lang,"_dependency_tree_metrics.txt",sep = ""),sep = "")
  raw_data <- read.table(path,header = FALSE,sep = " ",fill = TRUE,quote="", comment.char="") 
  colnames(raw_data) = c("vertices","degree_2nd_moment", "mean_length")
  raw_data = raw_data[order(raw_data$vertices),]
  # check validity
  valid_data <- raw_data %>% mutate(check = case_when(        
                                          (degree_2nd_moment >= (4-6)/vertices & degree_2nd_moment <= vertices-1) ~ "valid",
                                          TRUE ~ "invalid")) %>% filter(check == "valid")
  
  invalids = nrow(raw_data)-nrow(valid_data)
  print(paste("Invalid values for",lang,":",invalids))
  
  table_1$N[l] <- nrow(valid_data)
  table_1$mu_n[l] <- mean(valid_data$vertices)
  table_1$sd_n[l] <- sd(valid_data$vertices)
  table_1$mu_k[l] <- mean(valid_data$degree_2nd_moment)
  table_1$sd_k[l] <- sd(valid_data$degree_2nd_moment)
}
```


```{r}
Catalan = read.table("./data/Catalan_dependency_tree_metrics.txt", header = FALSE)
colnames(Catalan) = c("vertices","degree_2nd_moment", "mean_length")
Catalan = Catalan[order(Catalan$vertices),]
```


```{r}
mean_Catalan = aggregate(Catalan, list(Catalan$vertices), mean)
par(mfrow=c(1,2))

plot(mean_Catalan$vertices, mean_Catalan$degree_2nd_moment,
       xlab = "vertices", ylab = "mean mean degree_2nd_moment")
plot(log(mean_Catalan$vertices), log(mean_Catalan$degree_2nd_moment),
       xlab = "log(vertices)", ylab = "log(mean mean degree_2nd_moment)")

```


### attempt initial scaling
```{r}
plot(Catalan$vertices, Catalan$degree_2nd_moment,
     xlab = "vertices", ylab = "degree 2nd moment")
lines(mean_Catalan$vertices,mean_Catalan$degree_2nd_moment, col = "green")
lines(Catalan$vertices,
     (1 - 1/Catalan$vertices)*(5 - 6/Catalan$vertices), col = "red")
lines(Catalan$vertices,4-6/Catalan$vertices, col = "blue")
lines(Catalan$vertices,Catalan$vertices-1, col = "blue")
```


###################################################

# Non-linear regression

## MODEL 1

```{r}
#a_initial = 4
b_initial = 4
start1 <- Sys.time()
nonlinear_model = nls(degree_2nd_moment~(vertices/2)^b,data=Catalan,start = list(b = b_initial))
end1 <- Sys.time()
coef(nonlinear_model)[1]
end1-start1
```

### initial params with linear reg

```{r}
# log ⟨d⟩ = b log n + a′,
linear_model = lm(log(degree_2nd_moment)~log(vertices), Catalan)
a_linreg = exp(coef(linear_model)[1])
b_linreg = coef(linear_model)[2]
paste('a_linreg:',a_linreg,'b_linreg:',b_linreg, sep = ' ')

#b_initial = coef(linear_model)[1]
start1 <- Sys.time()
nonlinear_model = nls(degree_2nd_moment~(vertices/2)^b,data=Catalan,start = list(b = b_linreg))
end1 <- Sys.time()
coef(nonlinear_model)[1]
end1-start1
```

```{r}
#plot(linear_model)
```


```{r}
plot(nonlinear_model)
```

Heteroskedasticity and non normally distributed residuals!


## MODEL 2 - power law

```{r}
#f(n) = an^b
a_initial = 4
b_initial = 4
start1 <- Sys.time()
nonlinear_model = nls(degree_2nd_moment~a*(vertices)^b, data=Catalan, start = list(a = a_linreg, b = b_linreg))
end1 <- Sys.time()
coef(nonlinear_model)[1]
coef(nonlinear_model)[2]
end1-start1
```


```{r}
plot(nonlinear_model)
```

### BOX COX transformation

```{r}
k2m_BCOX <- caret::BoxCoxTrans(Catalan$degree_2nd_moment)
#print(k2m_BCOX)
Catalan <- cbind(Catalan, k2m_new=predict(k2m_BCOX, Catalan$degree_2nd_moment)) # append the transformed variable to cars
par(mfrow=c(1,2))
hist(Catalan$k2m_new)
hist(Catalan$degree_2nd_moment)
```


```{r}
model_2_BCIX = nls(k2m_new~a*(vertices)^b, data=Catalan, start = list(a = a_linreg, b = b_linreg))
plot(model_2_BCIX)
```

No difference, go for aggregation



#############################################

# AGGREGATED DATA

```{r}
grouped_Catalan <- Catalan %>% group_by(vertices) %>% dplyr::summarize(Mean_k2m = mean(degree_2nd_moment, na.rm=TRUE))
```


## Model 0 

```{r}
n <- length(grouped_Catalan$vertices)
RSS <- sum((grouped_Catalan$Mean_k2m - (1-1/grouped_Catalan$vertices)*(5-6/grouped_Catalan$vertices)))
p <- 0

# scores
s <- sqrt(RSS/(n - p))
AIC <- n*log(2*pi) + n*log(RSS/n) + n + 2*(p + 1)
paste("s:",s,"- AIC:", AIC)

# plot
plot(grouped_Catalan$vertices, grouped_Catalan$Mean_k2m,
    xlab = "vertices", ylab = "degree 2nd moment")
#lines(grouped_Catalan$vertices,grouped_Catalan$Mean_k2m, col = "green")
lines(grouped_Catalan$vertices,
    (1 - 1/grouped_Catalan$vertices)*(5 - 6/grouped_Catalan$vertices), col = "red")
lines(grouped_Catalan$vertices,4-6/grouped_Catalan$vertices, col = "blue")
lines(grouped_Catalan$vertices,grouped_Catalan$vertices-1, col = "blue")

```



## Model 1

```{r}
linear_model = lm(log(Mean_k2m)~log(vertices), grouped_Catalan)
a_linreg = exp(coef(linear_model)[1])
b_linreg = coef(linear_model)[2]

# reg
nonlinear_model = nls(Mean_k2m~(vertices/2)^b, data= grouped_Catalan, start = list(b = b_linreg))
b_opt = coef(nonlinear_model)["b"]

# scores
AIC <- AIC(nonlinear_model)
s <- sqrt(deviance(nonlinear_model)/df.residual(nonlinear_model))
paste("s:",s,"- AIC:", AIC)

plot(grouped_Catalan$vertices, grouped_Catalan$Mean_k2m,
    xlab = "vertices", ylab = "degree 2nd moment")
lines(grouped_Catalan$vertices, (grouped_Catalan$vertices/2)^b_opt , col = "red")
lines(grouped_Catalan$vertices,4-6/grouped_Catalan$vertices, col = "blue")
lines(grouped_Catalan$vertices,grouped_Catalan$vertices-1, col = "blue")
```

# Model 1+

```{r}
d_initial <- 7
model_1plus = nls(Mean_k2m~(vertices/2)^b + d, data= grouped_Catalan, start = list(b = b_linreg, d = d_initial))
b_opt <- coef(model_1plus)["b"]
d_opt <- coef(model_1plus)["d"]

# scores
RSS <- deviance(model_1plus)
AIC <- AIC(model_1plus)
s <- sqrt(deviance(model_1plus)/df.residual(model_1plus))
paste("s:",s,"- AIC:", AIC)

plot(grouped_Catalan$vertices, grouped_Catalan$Mean_k2m,
    xlab = "vertices", ylab = "degree 2nd moment")
lines(grouped_Catalan$vertices, (grouped_Catalan$vertices/2)^b_opt + d_opt , col = "red")
lines(grouped_Catalan$vertices,4-6/grouped_Catalan$vertices, col = "blue")
lines(grouped_Catalan$vertices,grouped_Catalan$vertices-1, col = "blue")

```



# Model 2

Same regression as before

```{r}
#f(n) = an^b
nonlinear_model = nls(Mean_k2m~a*(vertices)^b, data=grouped_Catalan, start = list(a = a_linreg, b = b_linreg))
a_opt <- coef(nonlinear_model)["a"]
b_opt <- coef(nonlinear_model)["b"]
paste("a_opt:",a_opt,"- b_opt:", b_opt)

# scores
RSS <- deviance(nonlinear_model)
AIC <- AIC(nonlinear_model)
s <- sqrt(deviance(nonlinear_model)/df.residual(nonlinear_model))
paste("s:",s,"- AIC:", AIC)

plot(grouped_Catalan$vertices, grouped_Catalan$Mean_k2m,
    xlab = "vertices", ylab = "degree 2nd moment")
lines(grouped_Catalan$vertices, a_opt*(grouped_Catalan$vertices)^b_opt , col = "red")
lines(grouped_Catalan$vertices,4-6/grouped_Catalan$vertices, col = "blue")
lines(grouped_Catalan$vertices,grouped_Catalan$vertices-1, col = "blue")
```


# Model 2+

```{r}
#f(n) = an^b + d
d_initial = 2
nonlinear_model = nls(Mean_k2m~a*(vertices)^b + d, data=grouped_Catalan, start = list(a = a_linreg, b = b_linreg, d = d_initial), control = list(printEval = T, maxiter = 100,warnOnly = TRUE))
a_opt <- coef(nonlinear_model)["a"]
b_opt <- coef(nonlinear_model)["b"]
d_opt <- coef(nonlinear_model)["d"]
paste("a_opt:",a_opt,"- b_opt:", b_opt)
help(nls)
# scores
RSS <- deviance(nonlinear_model)
AIC <- AIC(nonlinear_model)
s <- sqrt(deviance(nonlinear_model)/df.residual(nonlinear_model))
paste("s:",s,"- AIC:", AIC)

plot(grouped_Catalan$vertices, grouped_Catalan$Mean_k2m,
    xlab = "vertices", ylab = "degree 2nd moment")
lines(grouped_Catalan$vertices, a_opt*(grouped_Catalan$vertices)^b_opt + d_opt , col = "red")
lines(grouped_Catalan$vertices,4-6/grouped_Catalan$vertices, col = "blue")
lines(grouped_Catalan$vertices,grouped_Catalan$vertices-1, col = "blue")
```






# Model 3 


```{r}
linear_model_3 = lm(log(Mean_k2m)~vertices, grouped_Catalan)
a_linreg_3 = exp(coef(linear_model_3)[1])
c_linreg_3 = coef(linear_model_3)[2]

model_3 = nls(Mean_k2m~a*exp(c*vertices), data=grouped_Catalan, start = list(a = a_linreg_3, c = c_linreg_3))
a_opt <- coef(model_3)["a"]
c_opt <- coef(model_3)["c"]

# scores
RSS <- deviance(model_3)
AIC <- AIC(model_3)
s <- sqrt(deviance(model_3)/df.residual(model_3))
paste("s:",s,"- AIC:", AIC)

plot(grouped_Catalan$vertices, grouped_Catalan$Mean_k2m,
    xlab = "vertices", ylab = "degree 2nd moment")
lines(grouped_Catalan$vertices, a_opt*exp(c_opt*grouped_Catalan$vertices) , col = "red")
lines(grouped_Catalan$vertices,4-6/grouped_Catalan$vertices, col = "blue")
lines(grouped_Catalan$vertices,grouped_Catalan$vertices-1, col = "blue")

```










